# Generated by Django 5.2.7 on 2025-11-27 12:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_manage_accounts",
            field=models.BooleanField(
                default=False, help_text="User can be assigned as an account manager on policies."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_produce",
            field=models.BooleanField(
                default=False, help_text="User can be assigned as a producer on policies."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_account_manager_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Default account manager commission rate (%). Can be overridden per policy.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_producer_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Default producer commission rate (%). Can be overridden per policy.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Deprecated. Use default_producer_rate or default_account_manager_rate.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("producer", "Producer"),
                    ("account_manager", "Account Manager"),
                ],
                default="account_manager",
                help_text="Primary role (informational). Use capability flags for actual permissions.",
                max_length=32,
            ),
        ),
    ]
