version: "3.9"

services:
  web:
    build: .
    command: sh -c "uv sync --frozen --group dev && uv run --group dev python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ims
      POSTGRES_USER: ims
      POSTGRES_PASSWORD: ims
    volumes:
      - ims-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  ims-postgres-data:
