# Generated by Django 5.2.7 on 2025-11-27 11:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0002_alter_vehicle_vin"),
        ("clients", "0001_initial"),
        ("endorsements", "0002_endorsementdocument"),
        ("policies", "0002_alter_policy_account_manager_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("client_created", "Client Created"),
                            ("client_updated", "Client Updated"),
                            ("policy_created", "Policy Created"),
                            ("policy_updated", "Policy Updated"),
                            ("policy_bound", "Policy Bound"),
                            ("policy_cancelled", "Policy Cancelled"),
                            ("vehicle_created", "New Vehicle"),
                            ("vehicle_updated", "Edit Vehicle"),
                            ("vehicle_assigned", "Assign Vehicle"),
                            ("vehicle_removed", "Remove Vehicle"),
                            ("driver_created", "New Driver"),
                            ("driver_updated", "Edit Driver"),
                            ("driver_assigned", "Assign Driver"),
                            ("driver_removed", "Remove Driver"),
                            ("endorsement_created", "Endorsement Created"),
                            ("endorsement_started", "Endorsement Started"),
                            ("endorsement_completed", "Endorsement Completed"),
                            ("endorsement_cancelled", "Endorsement Cancelled"),
                            ("endorsement_updated", "Endorsement Updated"),
                            ("certificate_created", "Certificate Created"),
                            ("certificate_updated", "Certificate Updated"),
                            ("user_action", "User Action"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "transaction_name",
                    models.CharField(
                        help_text="Display name like 'Endorsement 09/17/2025' or 'Bind'",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Auto-generated log trail description"),
                ),
                ("notes", models.TextField(blank=True, help_text="Optional user notes")),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="clients.client",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="assets.driver",
                    ),
                ),
                (
                    "endorsement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="endorsements.endorsement",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="policies.policy",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="assets.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["client", "-timestamp"], name="common_acti_client__c272e2_idx"
                    ),
                    models.Index(
                        fields=["policy", "-timestamp"], name="common_acti_policy__530cb6_idx"
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"], name="common_acti_action__521350_idx"
                    ),
                ],
            },
        ),
    ]
