# Generated by Django 5.2.7 on 2025-10-18 11:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0002_alter_policy_account_manager_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Endorsement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("vehicles", "Vehicles"),
                            ("drivers", "Drivers"),
                            ("coverages", "Coverages"),
                            ("premium", "Premium"),
                            ("final", "Final"),
                        ],
                        default="client",
                        max_length=32,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "premium_change",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "fees_change",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "taxes_change",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "agency_fee_change",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "total_premium_change",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="policies.policy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsements_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EndorsementChange",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("vehicles", "Vehicles"),
                            ("drivers", "Drivers"),
                            ("coverages", "Coverages"),
                            ("premium", "Premium"),
                            ("final", "Final"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("address", "Address"),
                            ("vehicles", "Vehicles"),
                            ("drivers", "Drivers"),
                            ("coverages", "Coverages"),
                            ("premium", "Premium"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsement_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endorsement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="endorsements.endorsement",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
