# Generated by Django 5.2.7 on 2025-10-18 11:47

import apps.endorsements.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endorsements", "0001_initial"),
        ("lookups", "0004_alter_addresstype_options_alter_businesstype_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndorsementDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("vehicles", "Vehicles"),
                            ("drivers", "Drivers"),
                            ("coverages", "Coverages"),
                            ("premium", "Premium"),
                            ("final", "Final"),
                        ],
                        default="client",
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=512,
                        upload_to=apps.endorsements.models.endorsement_document_upload_to,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsement_documents",
                        to="lookups.documenttype",
                    ),
                ),
                (
                    "endorsement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="endorsements.endorsement",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsement_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
