# Generated by Django 5.2.7 on 2025-10-26 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="VIN must be 17 characters and exclude I, O, Q.",
                        regex="^[A-HJ-NPR-Z0-9]{17}$",
                    )
                ],
            ),
        ),
    ]
