# Generated by Django 5.2.7 on 2025-11-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_vehicle_vin"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="garaging_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Default garaging address for this vehicle.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="clients.address",
            ),
        ),
    ]
