# Generated by hand
from __future__ import annotations

from decimal import Decimal
import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("lookups", "0004_alter_addresstype_options_alter_businesstype_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralAgent",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "agency_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default commission percentage paid to the agency.",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="ReferralCompany",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Referral commission percentage applied to pure premium.",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="CarrierProduct",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("line_of_business", models.CharField(max_length=128)),
                ("insurance_company_name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(blank=True, max_length=64)),
                (
                    "new_business_commission_pct",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "renewal_commission_pct",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                ("is_retained", models.BooleanField(default=False)),
                ("is_premium_financed", models.BooleanField(default=False)),
                ("has_sweep_down", models.BooleanField(default=False)),
                ("has_sweep_payment", models.BooleanField(default=False)),
                ("has_auto_renew", models.BooleanField(default=False)),
                ("naic_code", models.CharField(blank=True, max_length=32)),
                ("am_best_number", models.CharField(blank=True, max_length=32)),
                ("am_best_rating", models.CharField(blank=True, max_length=32)),
                (
                    "general_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carrier_products",
                        to="policies.generalagent",
                    ),
                ),
            ],
            options={
                "ordering": ("insurance_company_name",),
                "unique_together": {("insurance_company_name", "line_of_business")},
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("policy_number", models.CharField(max_length=128)),
                ("effective_date", models.DateField()),
                ("maturity_date", models.DateField()),
                (
                    "account_manager_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "account_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="lookups.businesstype",
                    ),
                ),
                (
                    "carrier_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="policies.carrierproduct",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="lookups.financecompany",
                    ),
                ),
                (
                    "insurance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="lookups.insurancetype",
                    ),
                ),
                (
                    "policy_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="lookups.policytype",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_produced",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="policies.referralcompany",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="lookups.policystatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-effective_date", "policy_number"),
                "unique_together": {("client", "policy_number")},
            },
        ),
        migrations.CreateModel(
            name="PolicyFinancial",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "original_pure_premium",
                    models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True),
                ),
                (
                    "latest_pure_premium",
                    models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True),
                ),
                ("broker_fee", models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True)),
                ("taxes", models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True)),
                ("agency_fee", models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True)),
                (
                    "total_premium",
                    models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True),
                ),
                (
                    "down_payment",
                    models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True),
                ),
                (
                    "acct_manager_commission_amt",
                    models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True),
                ),
                (
                    "referral_commission_amt",
                    models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True),
                ),
                (
                    "policy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="policies.policy",
                    ),
                ),
            ],
            options={"ordering": ("policy",)},
        ),
        migrations.CreateModel(
            name="Coverage",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("coverage_type", models.CharField(max_length=128)),
                ("limits", models.CharField(blank=True, max_length=128)),
                ("deductible", models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="policies.policy",
                    ),
                ),
            ],
            options={"ordering": ("coverage_type",)},
        ),
    ]
