# Generated by Django 5.2.7 on 2025-11-27 12:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_alter_policy_account_manager_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="producer_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of pure premium paid to the producer for this policy.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="account_manager_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of pure premium paid to the account manager for this policy.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
