# Generated by Django 5.2.7 on 2025-12-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_add_producer_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyfinancial",
            name="producer_commission_amt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Commission amount paid to the producer.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policyfinancial",
            name="acct_manager_commission_amt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Commission amount paid to the account manager.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
