# Generated by Django 5.2.7 on 2025-10-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresstype',
            options={'ordering': ('name',), 'verbose_name': 'Address Type', 'verbose_name_plural': 'Address Types'},
        ),
        migrations.AlterModelOptions(
            name='businesstype',
            options={'ordering': ('name',), 'verbose_name': 'Business Type', 'verbose_name_plural': 'Business Types'},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'ordering': ('name',), 'verbose_name': 'Contact Type', 'verbose_name_plural': 'Contact Types'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('name',), 'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterModelOptions(
            name='financecompany',
            options={'ordering': ('name',), 'verbose_name': 'Finance Company', 'verbose_name_plural': 'Finance Companies'},
        ),
        migrations.AlterModelOptions(
            name='insurancetype',
            options={'ordering': ('name',), 'verbose_name': 'Insurance Type', 'verbose_name_plural': 'Insurance Types'},
        ),
        migrations.AlterModelOptions(
            name='licenseclass',
            options={'ordering': ('name',), 'verbose_name': 'License Class', 'verbose_name_plural': 'License Classes'},
        ),
        migrations.AlterModelOptions(
            name='policystatus',
            options={'ordering': ('name',), 'verbose_name': 'Policy Status', 'verbose_name_plural': 'Policy Statuses'},
        ),
        migrations.AlterModelOptions(
            name='policytype',
            options={'ordering': ('name',), 'verbose_name': 'Policy Type', 'verbose_name_plural': 'Policy Types'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ('name',), 'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
    ]
