# Generated by Django 5.2.7 on 2025-10-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0003_alter_addresstype_options_alter_businesstype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addresstype",
            options={"verbose_name": "Address Type", "verbose_name_plural": "Address Types"},
        ),
        migrations.AlterModelOptions(
            name="businesstype",
            options={"verbose_name": "Business Type", "verbose_name_plural": "Business Types"},
        ),
        migrations.AlterModelOptions(
            name="contacttype",
            options={"verbose_name": "Contact Type", "verbose_name_plural": "Contact Types"},
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={"verbose_name": "Document Type", "verbose_name_plural": "Document Types"},
        ),
        migrations.AlterModelOptions(
            name="financecompany",
            options={"verbose_name": "Finance Company", "verbose_name_plural": "Finance Companies"},
        ),
        migrations.AlterModelOptions(
            name="insurancetype",
            options={"verbose_name": "Insurance Type", "verbose_name_plural": "Insurance Types"},
        ),
        migrations.AlterModelOptions(
            name="licenseclass",
            options={"verbose_name": "License Class", "verbose_name_plural": "License Classes"},
        ),
        migrations.AlterModelOptions(
            name="policystatus",
            options={"verbose_name": "Policy Status", "verbose_name_plural": "Policy Statuses"},
        ),
        migrations.AlterModelOptions(
            name="policytype",
            options={"verbose_name": "Policy Type", "verbose_name_plural": "Policy Types"},
        ),
        migrations.AlterModelOptions(
            name="vehicletype",
            options={"verbose_name": "Vehicle Type", "verbose_name_plural": "Vehicle Types"},
        ),
    ]
